# Generated by Django 6.0a1 on 2025-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.BooleanField(default=False)),
                ('programmation_active', models.BooleanField(default=False)),
            ],
        ),
    ]
