# Generated by Django 6.0a1 on 2025-10-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prise',
            name='programmation_active',
        ),
        migrations.AddField(
            model_name='prise',
            name='heure_off',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prise',
            name='heure_on',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prise',
            name='horaire_active',
            field=models.BooleanField(default=False),
        ),
    ]
